language: android
jdk: oraclejdk8

branches:
  only:
    - master
    - test-builds
    - /^v([0-9]+)\.([0-9]+).*$/

android:
  components:
  - platform-tools
  - tools
  - build-tools-30.0.0
  - extra-android-m2repository

addons:
  apt:
    sources: deadsnakes
    packages: python3.7
  ssh_known_hosts: ssh.iitc.app

notifications:
  email:
    on_success: change
    on_failure: always

jobs:
  include:
    - stage: test-builds
      if: branch = test-builds
      env: BUILD_TYPE=test
    - stage: beta
      if: branch = master
      env: BUILD_TYPE=beta
    - stage: release
      if: NOT branch IN (test-builds, master)
      env: BUILD_TYPE=release

before_install:
  - yes | sdkmanager "platforms;android-30"
  - sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1
  - bundle install --path vendor/bundle

before_script:
  - wget https://iitc.app/deploy/localbuildsettings.py

script: ./build.py $BUILD_TYPE

deploy:
  # deploy to iitc site
  - provider: script
    skip_cleanup: true
    script: curl -s https://iitc.app/deploy/deploy.sh | bash -s -- $BUILD_TYPE
    on:
      all_branches: true

  # deploy beta to google play
  - provider: script
    skip_cleanup: true
    script: ./fastlane/push.sh
    on:
      branch: master

  # deploy release to google play
  - provider: script
    skip_cleanup: true
    script: ./fastlane/push.sh
    on:
      tags: true

  # deploy to github releases
  - provider: releases
    skip_cleanup: true
    name: $TRAVIS_TAG
    api_key:
      secure: KoJXTxCoatpFbQgbW1VBIh1ndtQIEmj68sANI+zOs54vi9XMCG3RM4cFn4y7YsSI/kz6XcoSC30SNnqedxHMPJyjrIWvVLKDTlbJswZmGhsslrZmClw3sFROKodVI5DoI0520mAfwzQ5PInPpSEfsPZQhA9ufv1wTZ/98q2efcRPu3J6riSdOZmqJ2A+veWpID3t3P57Lcjew+P3PdmUpwC9t6Yp4oQaYX4DZvMMpqK6s8E4EfOVQptaFAxYDIlAIWxNsfIJkx3jwmLdyaSwQL/fyesQ3fZRECKZTN7RM8/2nImuBZsq4uKS3nrKpLEXFTId45ET5N0fa23KXMLMM8NW0LlATLLWju+N7dP2HCeV5w2wxh+ToAR58XciiZLIsxI1IfF8WXloPax6DmJYksEKOenMYB/y/VASi5xbEhl89kdkxAaO6hAoVqKYo+xt7y3nPGSDUf+zfJnno5lPXgF3ctVAjmRBTWUSQQ5VhAeOp2LGg8ennzSkaLKxqyIxJ7F+n7Y0/QmG0uQzmerOjEEjVBsyVawRWjZGrDlog3Pq2S0n4vnbvbtUchwp/Fapjtg1f1pWy9Bzi1tnnE4ALJEmM894izxWH4vtDQu1+nkjKtLrkxgjk5yEuPj3n95ab64UO1To/x4YlyApmLkDeZIEMd+5siBTeGlB1V05Mr4=
    file_glob: true
    file:
    - ./build/release/*.apk
    - ./build/release/*.zip
    on:
      tags: true
