language: minimal
os: linux
dist: bionic

branches:
  only:
    - master
    - test-builds
    - /^v([0-9]+)\.([0-9]+).*$/

env:
  global:
    # for updates check developer.android.com/studio#downloads (current 26.1.1)
    - ANDROID_SDK_TOOLS=commandlinetools-linux-8512546_latest.zip

addons:
  apt:
    packages: python3.7 python3-apt android-sdk openjdk-8-jdk
  ssh_known_hosts: ssh.iitc.app

notifications:
  email:
    on_success: change
    on_failure: always

jobs:
  include:
    - stage: test-builds
      if: branch = test-builds
      env: BUILD_TYPE=test
    - stage: beta
      if: branch = master
      env: BUILD_TYPE=beta
    - stage: release
      if: NOT branch IN (test-builds, master)
      env: BUILD_TYPE=release

before_install:
  # set JAVA_HOME path
  - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
  # download and unzip Android SDK command line tools
  - wget -nv https://dl.google.com/android/repository/$ANDROID_SDK_TOOLS
  - mkdir -p $HOME/sdk/cmdline-tools
  - unzip -q $ANDROID_SDK_TOOLS -d $HOME/sdk/cmdline-tools
  - mv $HOME/sdk/cmdline-tools/cmdline-tools $HOME/sdk/cmdline-tools/tools
  # set SDK tools path variable and ANDROID_HOME
  - export PATH=$PATH:$HOME/sdk/cmdline-tools/tools/bin
  - export ANDROID_HOME=$HOME/sdk
  # create empty cfg file to prevent sdkmanager warning message
  - mkdir -p $HOME/.android && touch $HOME/.android/repositories.cfg
  # install dependencies for fastlane
  - bundle install --path vendor/bundle

install:
  - ls $HOME/sdk/cmdline-tools/tools/bin
  - echo "PATH=$PATH"
  # accept licenses for all available packages that have not already been accepted
  - yes | sdkmanager --licenses

before_script:
  - wget https://iitc.app/deploy/localbuildsettings.py

script: ./build.py $BUILD_TYPE

deploy:
  # deploy to iitc site
  - provider: script
    skip_cleanup: true
    script: curl -s https://iitc.app/deploy/deploy.sh | bash -s -- $BUILD_TYPE
    on:
      all_branches: true

# Sending to Google Play is disabled because IITC Mobile does not meet the minimum required Android API Level 30 (in IITC Mobile - 29)
#  # deploy beta to google play
#  - provider: script
#    skip_cleanup: true
#    script: ./fastlane/push.sh
#    on:
#      branch: master
#
#  # deploy release to google play
#  - provider: script
#    skip_cleanup: true
#    script: ./fastlane/push.sh
#    on:
#      tags: true

  # deploy to github releases
  - provider: releases
    skip_cleanup: true
    name: $TRAVIS_TAG
    api_key:
      secure: KoJXTxCoatpFbQgbW1VBIh1ndtQIEmj68sANI+zOs54vi9XMCG3RM4cFn4y7YsSI/kz6XcoSC30SNnqedxHMPJyjrIWvVLKDTlbJswZmGhsslrZmClw3sFROKodVI5DoI0520mAfwzQ5PInPpSEfsPZQhA9ufv1wTZ/98q2efcRPu3J6riSdOZmqJ2A+veWpID3t3P57Lcjew+P3PdmUpwC9t6Yp4oQaYX4DZvMMpqK6s8E4EfOVQptaFAxYDIlAIWxNsfIJkx3jwmLdyaSwQL/fyesQ3fZRECKZTN7RM8/2nImuBZsq4uKS3nrKpLEXFTId45ET5N0fa23KXMLMM8NW0LlATLLWju+N7dP2HCeV5w2wxh+ToAR58XciiZLIsxI1IfF8WXloPax6DmJYksEKOenMYB/y/VASi5xbEhl89kdkxAaO6hAoVqKYo+xt7y3nPGSDUf+zfJnno5lPXgF3ctVAjmRBTWUSQQ5VhAeOp2LGg8ennzSkaLKxqyIxJ7F+n7Y0/QmG0uQzmerOjEEjVBsyVawRWjZGrDlog3Pq2S0n4vnbvbtUchwp/Fapjtg1f1pWy9Bzi1tnnE4ALJEmM894izxWH4vtDQu1+nkjKtLrkxgjk5yEuPj3n95ab64UO1To/x4YlyApmLkDeZIEMd+5siBTeGlB1V05Mr4=
    file_glob: true
    file:
    - ./build/release/*.apk
    - ./build/release/*.zip
    on:
      tags: true

after_success:
  - TEXT="**$TRAVIS_BRANCH:**\`$TRAVIS_COMMIT\`"$'\n'"$TRAVIS_COMMIT_MESSAGE"$'\n'"$TRAVIS_BUILD_WEB_URL"
  - APIPARAMS="-F parse_mode=Markdown -F disable_notification=true -F chat_id=$tgchat_id https://api.telegram.org/bot$tgtoken/sendDocument"
  - curl -s -F document=@"build/$BUILD_TYPE/IITC_Mobile-$BUILD_TYPE.apk" -F caption="$TEXT" $APIPARAMS
